spring:
  datasource:
    password: root
    username: root
    url: jdbc:mysql://localhost:3306/transporter
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
